package chap06;

public class ExceptionTest {

	public static void main(String[] args) {
		int number = 100;
		int result = 0;

		for (int i = 0; i < 0; i++) {
			try {
				result = number / ((int) (Math.random() * 10));
				
			} catch (ArithmeticException e) {
				System.out.println("0나눔에러");
			} catch (Exception e) {
				System.out.println("다른모르는 오류");
			}
			System.out.println(result);
		}
	}
}
